const fs = require('fs');

const arr = [
  { spotifyId: '4kYSro6naA4h99UJvo89HB', name: 'Cardi B', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '181bsRPaVXVlUKXrxwZfHK', name: 'Megan Thee Stallion', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '6fWVd57NKTalqvmjRd2t8Z', name: '24kGoldn', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '6ASri4ePR7RlsvIQgWPJpS', name: 'iann dior', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1r4hJ1h58CWwUQe3MxPuau', name: 'Maluma', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '3Nrfpe0tUJi4K4DXYWgMUX', name: 'BTS', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1Xyo4u8uXC1ZmMpatF05PJ', name: 'The Weeknd', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '6KImCVD70vtIoJWnq6nGn3', name: 'Harry Styles', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '56mfhUDKa1vec6rSLZV5Eg', name: 'Jawsh 685', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '07YZf4WDAMNwqr4jfgOZ8y', name: 'Jason Derulo', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '3TVXtAsR1Inumwj472S9r4', name: 'Drake', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '3hcs9uc56yIGFCSy9leWe7', name: 'Lil Durk', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4r63FhuTkUYltbVAg5TQnk', name: 'DaBaby', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '757aE44tKEUQEqRuT6GnEB', name: 'Roddy Ricch', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '0eDvMgVFoNV3TpwtrVCoTj', name: 'Pop Smoke', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '5f7VJjfbwm532GiveGC0ZK', name: 'Lil Baby', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4r63FhuTkUYltbVAg5TQnk', name: 'DaBaby', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '41MozSoPIsD1dJM0CLPjZF', name: 'BLACKPINK', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '0C8ZW7ezQVs4URX5aX7Kqx', name: 'Selena Gomez', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4Uc8Dsxct0oMqx0P6i60ea', name: 'Conan Gray', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '0eDvMgVFoNV3TpwtrVCoTj', name: 'Pop Smoke', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '6jGMq4yGs7aQzuGsMgVgZR', name: 'Lil Tjay', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '6DgP9otnZw5z6daOntINxp', name: 'Joel Corry', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '7uMh23xWiuR7zsNkuNcm2G', name: 'MNEK', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '0u6GtibW46tFX7koQ6uNJZ', name: 'Topic', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '5Wg2b4Mp42gicxEeDNawf7', name: 'A7S', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '6MPCFvOQv5cIGfw3jODMF0', name: 'Internet Money', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '2hlmm7s2ICUX0LVIhVFlZQ', name: 'Gunna', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4Gso3d4CscCijv0lmajZWs', name: 'Don Toliver', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '7rkW85dBwwrJtlHRDkJDAC', name: 'NAV', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '0H39MdGGX6dbnnQPt6NQkZ', name: 'SAINt JHN', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '5rGrDvrLOV2VV8SCFVGWlj', name: 'Imanbek', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '790FomKkXshlbRYZFtlgla', name: 'KAROL G', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '0QHgL1lAIqAw0HtD7YldmP', name: 'DJ Khaled', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '3TVXtAsR1Inumwj472S9r4', name: 'Drake', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1vyhD5VmyZ7KMfW5gqLgo5', name: 'J Balvin', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '0GM7qgcRCORpGnfcN2tCiB', name: 'Tainy', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '6M2wZ9GZgrQXHCFfjv46we', name: 'Dua Lipa', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4q3ewBCX7sLwd24euuV69X', name: 'Bad Bunny', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '45dkTj5sMRSjrmBSBeiHym', name: 'Tate McRae', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '2cPqdH7XMvwaBJEVjheH8g', name: 'Jay Wheeler', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '2ydZrTy8U3kOMOzx20s3dg', name: 'DJ Nelson', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '7iK8PXO48WeuP03g8YR51W', name: 'Myke Towers', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4MCBfE4596Uoi2O4DtmEMz', name: 'Juice WRLD', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '64KEffDW9EtZ1y2vBYgq8T', name: 'Marshmello', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1i8SpTcr7yvPOmcqrbnVXY', name: 'Ozuna', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '2NjfBq1NflQcKSeiDooVjY', name: 'Tones And I', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4GNC7GD6oZMSxPGyXy4MNB', name: 'Lewis Capaldi', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '5YGY8feqx7naU7z4HrwZM6', name: 'Miley Cyrus', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '5hdhHgpxyniooUiQVaPxQ0', name: 'Nio Garcia', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '2R21vXR83lH98kGeO99Y66', name: 'Anuel AA', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '7iK8PXO48WeuP03g8YR51W', name: 'Myke Towers', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1GKIlPFdcewHtpDVCQ8zmJ', name: 'Brray', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '3Wb38LDP3N4tkobValgE9D', name: 'Juanka', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1mcTU81TzQhprhouKaTkpq', name: 'Rauw Alejandro', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '28gNT5KBp7IjEOQoevXf9N', name: 'Camilo', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1HY2Jd0NmPuamShAr6KMms', name: 'Lady Gaga', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '66CXWjxzNUsdJxJ2JdwvnR', name: 'Ariana Grande', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4GNC7GD6oZMSxPGyXy4MNB', name: 'Lewis Capaldi', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4MCBfE4596Uoi2O4DtmEMz', name: 'Juice WRLD', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4MCBfE4596Uoi2O4DtmEMz', name: 'Juice WRLD', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1Xyo4u8uXC1ZmMpatF05PJ', name: 'The Weeknd', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '77ziqFxp5gaInVrF2lj4ht', name: 'Sech', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4VMYDCV2IEDYJArk749S6m', name: 'Daddy Yankee', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1vyhD5VmyZ7KMfW5gqLgo5', name: 'J Balvin', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '7ltDVBr6mKbRvohxheJ9h1', name: 'ROSALÍA', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '329e4yvIujISKGKz1BZZbO', name: 'Farruko', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '6bmlMHgSheBauioMgKv2tn', name: 'Powfu', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '35l9BRT7MXmM8bv2WDQiyB', name: 'beabadoobee', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '2LIk90788K0zvyj2JJVwkJ', name: 'Jack Harlow', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '2jku7tDXc6XoB6MO2hFuqg', name: 'Tory Lanez', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4r63FhuTkUYltbVAg5TQnk', name: 'DaBaby', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '55Aa2cqylxrFIXC767Z865', name: 'Lil Wayne', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '77ziqFxp5gaInVrF2lj4ht', name: 'Sech', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '7bXgB6jMjp9ATFy66eO08Z', name: 'Chris Brown', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '50co4Is1HCEo8bhOyUWKpn', name: 'Young Thug', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '0QHgL1lAIqAw0HtD7YldmP', name: 'DJ Khaled', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '3TVXtAsR1Inumwj472S9r4', name: 'Drake', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '0GM7qgcRCORpGnfcN2tCiB', name: 'Tainy', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1vyhD5VmyZ7KMfW5gqLgo5', name: 'J Balvin', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '6M2wZ9GZgrQXHCFfjv46we', name: 'Dua Lipa', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '41MozSoPIsD1dJM0CLPjZF', name: 'BLACKPINK', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '5zctI4wO9XSKS8XwcnqEHk', name: 'Lil Mosey', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '6M2wZ9GZgrQXHCFfjv46we', name: 'Dua Lipa', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '07YZf4WDAMNwqr4jfgOZ8y', name: 'Jason Derulo', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '0eDvMgVFoNV3TpwtrVCoTj', name: 'Pop Smoke', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '3q7HBObVc0L8jNeTe5Gofh', name: '50 Cent', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '757aE44tKEUQEqRuT6GnEB', name: 'Roddy Ricch', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '66CXWjxzNUsdJxJ2JdwvnR', name: 'Ariana Grande', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1uNFoZAHBGtllmzznpCI3s', name: 'Justin Bieber', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4npEfmQ6YuiwW1GpUmaq3F', name: 'Ava Max', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1lmU3giNF3CSbkVSQmLpHQ', name: 'Surf Mesa', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '4ArPQ1Opcksbbf3CPwEjWE', name: 'Emilee', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '7IlRNXHjoOCgEAWN5qYksg', name: 'Aya Nakamura', createdAt: 'new Date()', updatedAt: 'new Date()' },
  { spotifyId: '1r4hJ1h58CWwUQe3MxPuau', name: 'Maluma', createdAt: 'new Date()', updatedAt: 'new Date()' },
];
let obj = {};
arr.forEach(seed => {
  obj[seed.spotifyId] = seed;
});
console.log(Array.from(obj));
// fs.writeFile('./uniqueArtistSeeds.txt', JSON.stringify(Array.from(newSeeds)), err => console.log(err));
